---
- name: Get list of available system groups
  shell: 'getent group | cut -f1 -d:'
  register: 'system_users__system_groups'
  changed_when: False

- name: Manage users default groups
  user:
    name: '{{ item.name }}'
    append: '{{ system_users__default_groups_append }}'
    groups: '{{ system_users__default_groups_list | intersect(system_users__system_groups.stdout_lines) | join(",") }}'
    state: 'present'
  with_flattened:
    - '{{ system_users__ansible }}'
    - '{{ system_users__list }}'
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.disabled is undefined or not item.disabled) and
         (item.groups is undefined))

- name: Manage users groups
  user:
    name: '{{ item.name }}'
    append: '{{ "yes" if system_users__default_groups_append and item.append is defined and item.append|bool else "no" }}'
    groups: '{{ item.groups | union(system_users__default_groups_list if item.append is defined and item.append|bool else []) | intersect(system_users__system_groups.stdout_lines) | join(",")  }}'
    state: 'present'
  with_flattened:
    - '{{ system_users__ansible }}'
    - '{{ system_users__list }}'
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.disabled is undefined or not item.disabled) and
         (item.groups is defined))
