---
- name: Manage system users home directories
  file:
    path: '{{ item.home | default("~" + item.name) }}'
    owner: '{{ item.home_owner | default(omit) }}'
    group: '{{ item.home_group | default(omit) }}'
    mode: '{{ item.home_mode | default(omit) }}'
    state: 'directory'
  with_flattened:
    - '{{ system_users__ansible }}'
    - '{{ system_users__list }}'
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.disabled is undefined or not item.disabled) and
         (item.createhome is undefined or item.createhome) and
         ((item.home_owner is defined and item.home_owner) or
          (item.home_group is defined and item.home_group) or
          (item.home_mode is defined and item.home_mode)))
