---
- name: Configure - Create, update, and remove system users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment|d(omit) }}"
    createhome: "{{ item.createhome|d(omit) }}"
    expires: "{{ item.expires|d(omit) }}"
    force: "{{ item.force|d(omit) }}"
    group: "{{ item.group|d(omit) }}"
    home: "{{ item.home|d(omit) }}"
    move_home: "{{ item.move_home|d(omit) }}"
    password: "{{ item.password|d('*') }}"
    remove: "{{ item.remove|d(omit) }}"
    shell: "{{ item.shell|d(omit) }}"
    skeleton: "{{ item.skeleton|d(omit) }}"
    system: "{{ item.system|d(omit) }}"
    uid: "{{ item.uid|d(omit) }}"
    update_password: "{{ item.update_password|d('on_create') }}"
    generate_ssh_key: "{{ item.generate_ssh_key|d(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits|d(omit) }}"
    ssh_key_comment: "{{ item.ssh_key_comment|d(omit) }}"
    ssh_key_file: "{{ item.ssh_key_file|d(omit) }}"
    ssh_key_passphrase: "{{ item.ssh_key_passphrase|d(omit) }}"
    ssh_key_type: "{{ item.ssh_key_type|d(omit) }}"
    state: "{{ (item.disabled is undefined or not item.disabled|bool)|ternary('present', 'absent') }}"
  with_flattened:
    - "{{ system_users__ansible }}"
    - "{{ system_users__list }}"
  when: (item.name is defined and item.name|trim and item.name != "root")
  tags: [ "configure" ]

- include: "homedirs.yml"
- include: "groups.yml"
